[package]
name = "riichi-tools-rs"
version = "0.0.61"
authors = ["harphield <harphield@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Riichi Mahjong tools library, mostly for WASM"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
enum-iterator = "0.5.0"
futures = "0.3.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.8"
wasm-bindgen-test = "0.3.8"
js-sys = "0.3.35"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = { version = "0.7", features = ["wasm-bindgen"] }
console_error_panic_hook = "0.1.6"
